enabled_group_name:
  type: string
  default: ""
  description:
    zh_CN: "为该群组的用户显示彩蛋"
    en: "Show easter egg for users in this group"
enable_easter_egg:
  type: bool
  default: false
  description:
    zh_CN: "启用彩蛋"
    en: "Enable easter egg"
force_global_easter_egg:
  type: bool
  default: false
  description:
    zh_CN: "强制启用全局彩蛋，即使不是4月1日"
    en: "Force global easter egg"
global_hint_text:
  type: string
  default: "Ctrl+Shift+I"
  description:
    zh_CN: "全局彩蛋提示"
    en: "Easter egg hint"
new_user_title:
  type: string
  default: "SVIP"
  description:
    zh_CN: "新的user-title文字"
    en: "New user-title"
avatar_replace_probability:
  type: float
  default: 0.1
  description:
    zh_CN: "替换头像的概率"
    en: "Probability of replacing avatar"
post_content_shuffle_probability:
  type: float
  default: 0.3
  description:
    zh_CN: "打乱帖子内容的概率"
    en: "Probability of shuffling post content"
post_content_shuffle_pairwise_probability:
  type: float
  default: 0.3
  description:
    zh_CN: "被打乱帖子中，每一对字符被交换的概率"
    en: "Probability of swapping each pair of characters in shuffled post content"
icon_shuffle_probability:
  type: float
  default: 0.3
  description:
    zh_CN: "打乱图标的概率"
    en: "Probability of shuffling icons"